# Generated by Django 3.0.3 on 2020-02-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='course',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='length',
            field=models.CharField(choices=[('5', '5'), ('15', '15'), ('30', '35'), ('60', '60'), ('75', '75'), ('90', '90'), ('120', '120')], default='5', max_length=17),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subject',
            field=models.CharField(choices=[('APMA', 'MATH'), ('CS', 'COMPUTER SCIENCE'), ('GCOM', 'BUSINESS'), ('BIOL', 'BIOLOGY'), ('CHEM', 'CHEMISTRY')], default='CS', max_length=17),
        ),
    ]
