# Generated by Django 3.0.3 on 2020-02-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='course',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='------', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='number',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subject',
            field=models.CharField(choices=[('Subject', 'SUBJECT'), ('APMA', 'MATH'), ('CS', 'COMPUTER SCIENCE'), ('GCOM', 'BUSINESS'), ('BIOL', 'BIOLOGY'), ('CHEM', 'CHEMISTRY')], default='Subject', max_length=17),
        ),
    ]
