# Generated by Django 3.0.3 on 2020-02-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200220_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='length',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='number',
        ),
        migrations.AddField(
            model_name='homepage',
            name='courseNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='time',
            field=models.CharField(choices=[('5', '5 minutes'), ('15', '15 minutes'), ('30', '35 minutes'), ('60', '1 hour'), ('75', '1 hour 15 minutes'), ('90', '1.5 hour'), ('120', '2 hours')], default='5', max_length=17),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subject',
            field=models.CharField(choices=[('Subject', 'SUBJECT'), ('APMA', 'Math'), ('CS', 'Computer Science'), ('GCOM', 'Business'), ('BIOL', 'Biology'), ('CHEM', 'Chemistry')], default='Subject', max_length=17),
        ),
    ]
