# Generated by Django 3.0.2 on 2020-02-23 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200220_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='length',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='number',
        ),
        migrations.AddField(
            model_name='homepage',
            name='courseNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='time',
            field=models.CharField(choices=[('5', '5 minutes'), ('15', '15 minutes'), ('30', '35 minutes'), ('60', '1 hour'), ('75', '1 hour 15 minutes'), ('90', '1.5 hour'), ('120', '2 hours')], default='5', max_length=17),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subject',
            field=models.CharField(choices=[('Subject', 'SUBJECT'), ('APMA', 'Math'), ('CS', 'Computer Science'), ('GCOM', 'Business'), ('BIOL', 'Biology'), ('CHEM', 'Chemistry')], default='Subject', max_length=17),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('london', django.db.models.manager.Manager()),
            ],
        ),
    ]
